version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: fcf3-catalog-app
    tty: true
    ports:
      - 3009:3000
    depends_on:
      - db
    volumes:
      - .:/home/node/app